name: documentation

on:
  workflow_dispatch:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - docs/**
      - fluent.*/docs/**
      - fluent.*/fluent/**
      - fluent.*/setup.cfg
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - fluent.*/docs/**
      - fluent.*/fluent/**
      - fluent.*/setup.cfg

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install ./fluent.docs
      - run: ./scripts/build-docs python-fluent
      - uses: actions/upload-artifact@v4
        with:
          name: html
          path: |
            _build/python-fluent
            !_build/**/.buildinfo

  #publish:
  #  name: publish
  #  needs: [build]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: html
  #        path: _build
  #    - name: Deploy 🚀
  #      uses: JamesIves/github-pages-deploy-action@v4.4.1
  #      with:
  #        branch: gh-pages # The branch the action should deploy to.
  #        folder: _build # The folder the action should deploy.
  #        clean: true # Automatically remove deleted files from the deploy branch
  #        dry-run: ${{ github.event_name == 'pull_request' }}
